### ISSUE TITLE
What do you think about integrating keycloak in your simple infrastructure? 

### ISSUE THREAD

**Issue by viguice** [ugenef/simple-infrastructure#2]
Hi,

I like very much your article and thanks for sharing your work. I would like to implement myself a similar solution. However, I am interested to include also keycloak for authentication. It would be in my view more complete as a base for my infrastructure. 
Did you try? In principle, Grafana can delegate the authentication to keycloak.
I used another available git to make a test (https://github.com/viguice/keycloak-traefik-grafana-compose). This one based on keycloak and grafana but without traefik. So I have added labels for traefik but I am struggling to interface grafana with keycloak.
If you have a moment to have a look and to help me, I would be wonderful.

Thanks,

Cédric

**Comment by ugenef** [comment]
Hey. Thanks for reaching me.
The purpose of my repo is to make a solid basis for launching new projects. I think Keycloack doesn't fit into my compose because  not every new project needs it as commonly as it needs grafana.
However, for solving your problem, I would advise you to start both grafana and keykloak containers with max logging available and debug the problem that way.  F12 in your browser also might help. It looks like keykloak threat grafana or traefik as untrusted clients or so.
